[package]
name = "gon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
crossterm = "0.25.0"
futures = "0.3.25"
log = "0.4.26"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.11"
tokio-util = { version = "0.7.4", features = ["rt"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.43.0", features = [
  "UI_Notifications_Management",
  "Foundation_Collections",
  "ApplicationModel",
  "Storage_Streams",
  "Graphics_Imaging",
]}
